name: pst-gti-artemis-validation
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  pst-gti-artemis:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: venv activate Linux
      run: |
        mkdir test-venv
        cd test-venv
        python -m venv .
        source ./bin/activate
        echo "VIRTUAL_ENV: $VIRTUAL_ENV"       
    - name: Install dependencies
      #working-directory: /home/runner/work/Calculator/Calculator/test-venv
      run: |
        python -m venv pip install --upgrade pip /test-venv
        python -m venv pip install pyyaml /test-venv
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
