name: pst-gti-artemis-validation
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  pst-gti-artemis:
    runs-on: [self-hosted, linux, general]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: venv activate Linux
      run: |
        mkdir test-venv
        cd test-venv
        python -m venv .
        source ./bin/activate
        echo "VIRTUAL_ENV: $VIRTUAL_ENV"       
    - name: Install dependencies
      working-directory: /uni/test/app/venv
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        echo "VIRTUAL_ENV: $VIRTUAL_ENV"
